# Generated by Django 5.2.17 on 2026-09-20 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='PROVEN TRACK RECORD', max_length=120)),
                ('text', models.TextField(default='We did 100+ projects as of now, 200+ clients satisfied across colleges!')),
                ('stats_badge', models.CharField(default='100+ Projects Completed · 200+ Satisfied Students', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='admin_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='feedback_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
