# Generated by Django 5.2.17 on 2026-09-21 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_heroannouncement_projectrequest_admin_responded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementCompanyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('ece', 'ECE (Electronics & Communication)'), ('cse', 'CSE (Computer Science)'), ('it', 'IT (Information Technology)'), ('eee', 'EEE (Electrical & Electronics)')], max_length=10)),
                ('company_name', models.CharField(max_length=200)),
                ('role_title', models.CharField(max_length=200)),
                ('job_type', models.CharField(default='Full-time', max_length=80)),
                ('apply_link', models.URLField(max_length=500)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('batch_eligibility', models.CharField(blank=True, max_length=120)),
                ('salary_or_stipend', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['deadline', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentJobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('company_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_applications', to='projects.placementcompanylink')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('student', 'company_link')},
            },
        ),
    ]
