# Generated by Django 5.2.17 on 2026-09-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_placementcompanylink_studentjobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementcompanylink',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
