import React, {useEffect, useState} from 'react'
import {createRoot} from 'react-dom/client'
import './styles.css'

const API = import.meta.env.VITE_API_URL || '/api'
const SOCKET_ORIGIN = API.startsWith('http') ? API.replace(/^http/, 'ws').replace(/\/api$/, '') : `${location.protocol === 'https:' ? 'wss' : 'ws'}://${location.host}`
const statuses = ['received', 'confirmed', 'doing', 'done', 'delivered']
const nice = {received:'Received', confirmed:'Confirmed', doing:'In Progress', done:'Done', delivered:'Delivered'}
async function request(path, options={}) {
  const token = localStorage.getItem('cc_token')
  const res = await fetch(API + path, {headers:{'Content-Type':'application/json', ...(token?{Authorization:`Bearer ${token}`}:{})}, ...options})
  const data = await res.json().catch(()=>({}))
  if (!res.ok) throw new Error(data.detail || Object.values(data).flat().join(' ') || 'Something went wrong')
  return data
}
function Auth({onLogin}) {
  const [mode,setMode]=useState('login'), [error,setError]=useState(''), [busy,setBusy]=useState(false)
  async function submit(e){e.preventDefault(); setBusy(true);setError(''); const f=Object.fromEntries(new FormData(e.target));try {if(mode==='signup') await request('/auth/register/',{method:'POST',body:JSON.stringify(f)}); const data=await request('/auth/login/',{method:'POST',body:JSON.stringify({username:f.email,password:f.password})});localStorage.setItem('cc_token',data.access);onLogin()}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <main className="auth"><section className="hero"><span className="logo">◉ College Circuit</span><h1>Bring your project<br/><i>to life.</i></h1><p>From bright campus ideas to polished digital projects — find a practical freelance partner here.</p><div className="chips"><span>Web apps</span><span>IoT builds</span><span>AI / ML</span></div></section><section className="authbox"><div><p className="eyebrow">WELCOME TO COLLEGE CIRCUIT</p><h2>{mode==='login'?'Welcome back':'Start your project'}</h2><p className="muted">{mode==='login'?'Log in to check your project updates.':'Create your student account in seconds.'}</p></div><form onSubmit={submit}>{mode==='signup'&&<label>Full name<input name="name" required placeholder="Your name"/></label>}<label>{mode==='login'?'Email address or username':'Email address'}<input name="email" type={mode==='login'?'text':'email'} required placeholder={mode==='login'?'you@college.edu or root':'you@college.edu'}/></label><label>Password<input name="password" type="password" minLength="8" required placeholder="At least 8 characters"/></label>{error&&<p className="error">{error}</p>}<button disabled={busy}>{busy?'Please wait…':mode==='login'?'Log in':'Create account'} <b>→</b></button></form><p className="switch">{mode==='login'?"New here? ":'Already a member? '}<a onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Create an account':'Log in'}</a></p></section></main>
}
function Status({status}){return <span className={'status '+status}>{nice[status]}</span>}
function Timeline({status}){let cur=statuses.indexOf(status);return <div className="timeline">{statuses.map((s,i)=><React.Fragment key={s}><div className={i<=cur?'step active':'step'}><span>{i<cur?'✓':i+1}</span><small>{nice[s]}</small></div>{i<4&&<div className={i<cur?'line active':'line'}/>}</React.Fragment>)}</div>}
function NewRequest({onCreated}) {const [error,setError]=useState(''); async function submit(e){e.preventDefault();try{const data=await request('/projects/',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});onCreated(data);e.target.reset()}catch(e){setError(e.message)}}return <section className="panel formpanel"><div><p className="eyebrow">NEW REQUEST</p><h2>What are we building?</h2><p className="muted">Share your idea — we’ll contact you to discuss requirements and pricing.</p></div><form onSubmit={submit} className="projectform"><label>Project title<input name="title" required placeholder="e.g. IOT Automatic car or web pages"/></label><label>Category<select name="category"><option value="iot">IoT Project</option><option value="web">Web Development</option><option value="ai">AI / Machine Learning</option><option value="mobile">Mobile App</option><option value="design">UI / UX Design</option><option value="other">Other</option></select></label><label>College / university<input name="college" required placeholder="Your college name"/></label><label>Phone number<input name="phone" type="tel" inputMode="numeric" pattern="[6-9][0-9]{9}" minLength="10" maxLength="10" required title="Enter a valid 10-digit Indian mobile number" placeholder="10-digit mobile number" onInput={e=>e.currentTarget.value=e.currentTarget.value.replace(/\D/g,'').slice(0,10)}/><small className="fieldhint">10 digits, beginning with 6, 7, 8, or 9</small></label><label>Target deadline<input name="deadline" type="date"/></label><label className="wide">Tell us about your requirements<textarea name="description" required placeholder="Features, technology preferences, reference links, and anything else useful…"/></label>{error&&<p className="error">{error}</p>}<button>Send project request <b>→</b></button></form></section>}
function Student({user}) {const [projects,setProjects]=useState([]),[view,setView]=useState('projects');const load=()=>request('/projects/').then(setProjects).catch(console.error);useEffect(()=>{load();let socket;try {const t=localStorage.getItem('cc_token');socket=new WebSocket(`${SOCKET_ORIGIN}/ws/projects/?token=${t}`);socket.onmessage=load}catch{}const timer=setInterval(load,30000);return()=>{socket?.close();clearInterval(timer)}},[]);return <><Header user={user} view={view} setView={setView}/><main className="dashboard"><div className="intro"><p className="eyebrow">STUDENT DASHBOARD</p><h1>Hi, {user.name.split(' ')[0]} <span>✦</span></h1><p>Track your requests and let’s make something exceptional.</p></div>{view==='new'?<NewRequest onCreated={()=>{load();setView('projects')}}/>:<><div className="sectionhead"><h2>Your project requests</h2><button onClick={()=>setView('new')}>+ New request</button></div>{projects.length?<div className="cards">{projects.map(p=><article className="project" key={p.id}><div className="cardtop"><span className="category">{p.category_label}</span><Status status={p.status}/></div><h3>{p.title}</h3><p>{p.description}</p><Timeline status={p.status}/><div className="meta"><span>Updated {new Date(p.updated_at).toLocaleDateString()}</span>{p.quote&&<b>Quote: ₹{p.quote}</b>}</div>{p.admin_note&&<div className="note">✦ {p.admin_note}</div>}</article>)}</div>:<div className="empty"><b>Your ideas belong here.</b><p>Submit your first project request and we’ll reach out to understand it better.</p><button onClick={()=>setView('new')}>Create a request</button></div>}</>}</main></>}
function Header({user,view,setView}){return <header><a className="logo">◉ College Circuit</a><nav className="mainnav"><button className={view==='projects'?'active':''} onClick={()=>setView('projects')}>My Projects</button><button className="requestnav" onClick={()=>setView('new')}>+ New Request</button>{user.is_staff&&<button className={view==='admin'?'active':''} onClick={()=>setView('admin')}>Admin</button>}</nav><div className="user"><span>{user.name.slice(0,1).toUpperCase()}</span><b>{user.name}</b><button className="logout" onClick={()=>{localStorage.clear();location.reload()}}>Log out</button></div></header>}
function Admin({user}) {const [items,setItems]=useState([]),[selected,setSelected]=useState(null);const load=()=>request('/projects/admin/').then(setItems);useEffect(()=>{load()},[]);async function save(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.target));await request('/projects/admin/'+selected.id+'/',{method:'PATCH',body:JSON.stringify(data)});setSelected(null);load()}return <><Header user={user} view="admin" setView={()=>{}}/><main className="dashboard"><div className="intro"><p className="eyebrow">OPERATIONS</p><h1>Admin workspace</h1><p>{items.length} student requests in the pipeline.</p></div><div className="admin-grid"><section className="panel requests"><h2>All requests</h2>{items.map(p=><button className="requestrow" onClick={()=>setSelected(p)} key={p.id}><div><b>{p.title}</b><small>{p.student.name} · {p.student.email}</small></div><Status status={p.status}/></button>)}</section>{selected?<section className="panel detail"><p className="eyebrow">REQUEST #{selected.id}</p><h2>{selected.title}</h2><p>{selected.description}</p><div className="contact"><b>Contact</b><a href={'mailto:'+selected.student.email}>{selected.student.email}</a><a href={'tel:'+selected.phone}>{selected.phone}</a><span>{selected.college}</span></div><form onSubmit={save}><label>Project status<select name="status" defaultValue={selected.status}>{statuses.map(s=><option value={s} key={s}>{nice[s]}</option>)}</select></label><label>Quote (₹)<input name="quote" type="number" defaultValue={selected.quote||''}/></label><label>Client-facing update<textarea name="admin_note" defaultValue={selected.admin_note||''} placeholder="Shown in the student dashboard"/></label><button>Save & notify student</button></form></section>:<section className="panel detail muted">Select a request to view contact details and update its status.</section>}</div></main></>}
function App(){const [user,setUser]=useState(null);useEffect(()=>{if(localStorage.cc_token)request('/auth/me/').then(setUser).catch(()=>localStorage.clear())},[]);if(!user)return <Auth onLogin={()=>request('/auth/me/').then(setUser)}/>;return user.is_staff?<Admin user={user}/>:<Student user={user}/>}
createRoot(document.getElementById('root')).render(<App/>)
